Update nf-wdm-porequestpowerirp.md
MicrosoftDocs/windows-driver-docs-ddi pull request #1088
Opened 2021-05-10 06:19 UTC by aktsuda

Add the case about an Avstream minidriver which is a power policy owner, but doesn't need to call PoRequestPowerIrp by itself. KS calls it instead.

2021-05-14 01:24 UTC, chcurlet-msft requested changes
Minor nit on wording, plus Jacob's suggestion was to potentially find a more relevant docs section for this info.

2021-05-14 01:24 UTC, chcurlet-msft commented on wdk-ddi-src/content/wdm/nf-wdm-porequestpowerirp.md
> +> An Avstream minidriver doesn't have to call <b>PoRequestPowerIrp</b> by itself. An Avstream minidriver is a device power policy owner, but KS (ksthunk.sys) sees a system power IRP it automatically
Minor wording revision suggestion (remove some redundancy):  "An Avstream minidriver doesn't have to call <b>PoRequestPowerIrp</b> by itself. An Avstream minidriver is a device power policy owner, but when KS (ksthunk.sys) receives a system power IRP it automatically sends a corresponding device power IRP to the Avstream device."

2021-05-20 23:12 UTC, tedhudek commented
Assigning to you Akihisa, while the wording is still in discussion. Please assign back to me when it's ready

2021-05-27 19:14 UTC, tedhudek commented
Replaced by https://github.com/MicrosoftDocs/windows-driver-docs/pull/2804

2021-05-27 19:14 UTC, closed without merging